#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os
from ec_local_param import LocalParam

__author__ = 'Pavan Mahalingam'


# general parameters -----------------------------------------------------------------------------------------------
class EcAppParamGeneral(LocalParam):
    """
    General application parameters
    """
    #: Static files root (copied from :any:`LocalParam`)
    gcm_staticRoot = LocalParam.gcm_appRoot
    #: Application name (used in many contexts like logger names, cookie name, etc)
    gcm_appName = 'ConspiSuck'
    #: Application version (dev version with three figures)
    gcm_appVersion = '0.0.0'
    #: App description (used in title of HTML pages ...)
    gcm_appTitle = 'FB scraping of conspirationist pages'
    #: File name of the reboot file
    gcm_rebootFile = 'reboot.txt'
    #: Local time zone
    gcm_timeZone = 'Asia/Calcutta'


# HTTP server parameters -------------------------------------------------------------------------------------------
class EcAppParamHttp(LocalParam):
    """
    HTTP server parameters
    """
    #: Cookie lifetime in days (100 years)
    gcm_cookiePersistence = 365*100
    #: Cookie name for the terminal ID
    gcm_sessionName = 'ECTerminalID_{0}'.format(EcAppParamGeneral.gcm_appName)


# Database parameters ----------------------------------------------------------------------------------------------
class EcAppParamDatabase(LocalParam):
    """
    Database parameters
    """
    #: Database name
    gcm_dbDatabase = 'ConspiSuck'
    #: Database username (copied from :any:`LocalParam`)
    gcm_dbUser = LocalParam.gcm_dbUserLocal
    #: Database password (copied from :any:`LocalParam`)
    gcm_dbPassword = LocalParam.gcm_dbPasswordLocal
    #: Min size of DB connection pool
    gcm_connectionPoolMinCount = 3
    #: Max size of DB connection pool
    gcm_connectionPoolMaxCount = 10
    #: Flag to disable the connection pool feature. If `True` then new connection creation on each request.
    #: Not active at the moment.
    gcm_noConnectionPool = False


# Logging parameters -----------------------------------------------------------------------------------------------
class EcAppParamLogging(LocalParam):
    """
    Logging parameters
    """
    #: Recipients of e-mail messages generated by the logging system
    gcm_mailRecipients = ['nicolas.reimen@gmail.com']
    #: Location of CSV log file
    gcm_logFile = os.path.join(EcAppParamGeneral.gcm_appRoot, 'Log/ec_log.csv')


# Facebook specific parameters -------------------------------------------------------------------------------------
class EcAppParamFacebook(LocalParam):
    """
    Facebook download parameters
    """
    #: Minimum size of images to be downloaded (in both directions)
    gcm_minImageSize = 100
    #: True --> Expand comments list for each story
    gcm_expandComments = True
    #: Version of the FB API
    gcm_api_version = 'v2.10'
    #: max number of posts retrieved from a page
    gcm_max_post = 50
    #: max number of days a post will be updated after its creation
    gcm_days_depth = 14
    #: number of days after which the detailed liked list of a post will be fetched
    gcm_likes_depth = 4
    #: number of elements retrieved in one request (API param)
    gcm_limit = 100
    #: wait period after a request limit hit (in seconds)
    gcm_wait_fb = 60 * 60
    #: number of requests after which the token must be renewed (no longer used because of long-duration tokens)
    gcm_token_lifespan = 2000


# Browser driver parameters ----------------------------------------------------------------------------------------
class EcAppParamBrowser(LocalParam):
    """
    Browser driver parameters
    """
    #: Headless browser screen size (Width)
    gcm_headlessWidth = 1200
    #: Headless browser screen size (Height)
    gcm_headlessHeight = 2000
    #: Non-headless browser screen size (Width)
    gcm_width = 1200
    #: Non-headless browser screen size (Height)
    gcm_height = 1000


# Results display parameters ---------------------------------------------------------------------------------------
class EcAppParamDisplay(LocalParam):
    """
    Display application parameters
    """
    #: Maximum number of sessions to show
    gcm_sessionDisplayCount = 300


class EcAppParam(EcAppParamDisplay,
                 EcAppParamBrowser,
                 EcAppParamFacebook,
                 EcAppParamLogging,
                 EcAppParamDatabase,
                 EcAppParamHttp,
                 EcAppParamGeneral):
    """
    Static class containing all the global parameters which do not depend on the environment (dev/qualif/prod).
    """


class TestA:
    cm1 = 'toto'


class TestB(TestA):
    cm2 = 'tutu'

# ---------------------------------------------------- Main section ----------------------------------------------------
if __name__ == "__main__":
    print(TestA.cm1)
    print(TestB.cm1)

    print(EcAppParam.gcm_httpPort)
