#!/usr/bin/python3
# -*- coding: utf-8 -*-

__author__ = 'Pavan Mahalingam'


class LocalParamGeneral:
    #: True --> Production environment
    gcm_prodEnv = False
    #: global root path
    gcm_appRoot = '/home/fi11222/disk-partage/Dev/ConspiSuck/'


# HTTP server parameters
class LocalParamHttp:
    #: domain name (= 'localhost' except for prod environment)
    gcm_appDomain = 'localhost'
    #: TCP/IP port number on which the server is listening (use two different ones to have multiple
    #: servers on the same machine)
    gcm_httpPort = 9080


# Database parameters
class LocalParamDatabase:
    #: Database server name (normally 'localhost' but could be different in non-prod env)
    gcm_dbServer = 'localhost'
    #: Database connection user name
    gcm_dbUserLocal = 'postgres'
    #: Database connection password
    gcm_dbPasswordLocal = 'murugan!'


# Logging
class LocalParamLogging:
    #: If True then maximum level of logging
    gcm_debugModeOn = True
    #: If True then only INFO level log messages are kept
    gcm_verboseModeOn = True
    #: If True then all messages are sent to TB_EC_DEBUG
    gcm_debugToDB = True
    #: If True then all messages above WARNING level are sent by mail
    gcm_warningsToMail = False
    #: If True then do not load browscap
    gcm_skipBrowscap = True
    #: Address of the sender for the e-mail messages generated by the logging system
    gcm_mailSender = 'nicolas.reimen@gmail.com'
    #: Address of the smtp server to send the e-mail messages generated by the logging system
    gcm_smtpServer = 'smtp.gmail.com'
    # Smtp2Go uses the same authentication sequence as Gmail
    # gcm_smtpServer = 'mail.smtp2go.com'
    #: If True, use Gmail TLS authentication to connect to the smtp server (SES)
    gcm_gmailSmtp = True
    #: Gmail/TLS password
    gcm_mailSenderPassword = '17Siratal'
    #: If True, use Amazon AWS specific method to connect to the smtp server (SES)
    gcm_amazonSmtp = False
    #: Amazon SES ID (not used)
    gcm_sesIamUser = ''
    #: Amazon SES user
    gcm_sesUserName = ''
    #: Amazon SES pwd
    gcm_sesPassword = ''


# Browser Driver
class LocalParamBrowser:
    #: Browser type
    gcm_browser = 'Chrome'
    #: Headless on/off switch
    gcm_headless = True


# Facebook Download
class LocalParamFacebook:
    #: Average browser driver life span (in hours)
    gcm_bdLifeAverage = 1
    #: +/- value (in hours) around average between which the browser driver life span is chosen at random
    gcm_bdLifeDiameter = .25
    #: Number of tries before attempts to get more stories are abandoned
    gcm_expansionCount = 3
    #: Maximum number of stories downloaded per profile
    gcm_max_story_count = 30
    #: False --> do not capture images within stories
    gcm_getImages = True
    #: False --> do not start the Facebook download thread
    gcm_startGathering = True
    #: Sequential number of the first phantom to start download loop with
    gcm_startPhantomNo = 0
    #: Min delay between main loop actions
    gcm_bkgMinDelay = 30
    #: Max delay between main loop actions
    gcm_bkgMaxDelay = 90
    #: Min delay between stories download
    gcm_storiesMinDelay = 10
    #: Max delay between stories download
    gcm_storiesMaxDelay = 30
    #: Url to the login page for API token access
    gcm_api_login_url = 'http://localhost/FBWatch/FBWatchLogin.html'
    #: Launch the OCR thread ?
    gcm_ocr_thread = True


class LocalParam(LocalParamFacebook,
                 LocalParamBrowser,
                 LocalParamLogging,
                 LocalParamDatabase,
                 LocalParamHttp,
                 LocalParamGeneral):
    """
    Static class containing the global parameters which (may) depend on the environment (dev/qualif/prod).
    """
